markdown: kramdown
highlighter: rouge
permalink: /posts/:title
name: Vamsee Jasti
blog_name: Sent from my ipod
url: jasti.github.io
description: Ramblings & Nerdery
twitter: vamseejasti
github: jasti
tags:
- jekyll
- code
