markdown: rdiscount
highlighter: pygments
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Vamsee Jasti
blog_name: Sent from my ipod
url: jasti.github.io
description: Thoughts, Nerdery & Experiments
twitter: vamseejasti
github: jasti
tags:
- jekyll
- code
