markdown: kramdown
highlighter: rouge
permalink: /posts/:title
name: Vamsee Jasti
blog_name: Sent from my ipod
url: jasti.github.io
description: It didn't happen if I didn't write it down
twitter: vamseejasti
github: jasti
tags:
- jekyll
- code
